name: Crypto Screener (Daily 11PM WAT)

on:
  schedule:
    - cron: "0 22 * * *"   # Runs daily at 22:00 UTC (11PM WAT)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Crypto Screener
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TRADINGVIEW_USER: ${{ secrets.TRADINGVIEW_USER }}
          TRADINGVIEW_PASS: ${{ secrets.TRADINGVIEW_PASS }}
          CRYPTO_URL: ${{ secrets.CRYPTO_URL }}
        run: node main.js
